pipeline {
    agent any
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Select the environment to build the Student Management System')
    }
    stages {
        stage('Checkout') {
            steps {
                // Adjust repo URL to your repository details
                git branch: 'main', url: 'https://github.com/yogan77/student_management_system.git'
            }
        }
        stage('Show Parameter') {
            steps {
                echo "Selected deployment environment: ${params.ENVIRONMENT}"
            }
        }
        stage('Build for Environment') {
            steps {
                echo "Building Student Management and Academic Performance System for the ${params.ENVIRONMENT} environment..."
            }
        }
    }
}
