pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/yogan77/student_management_system.git'
            }
        }
        stage('Generate Academic Report') {
            steps {
                bat 'python app.py'
            }
        }
        stage('Archive Report Artifact') {
            steps {
                archiveArtifacts artifacts: 'student_report.txt', fingerprint: true
            }
        }
    }
}
