pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/yogan77/student_management_system.git'
            }
        }
        stage('Generate Report') {
            steps {
                // Tells Jenkins to go inside the project2 folder before running Python
                dir('project2') {
                    bat 'python app.py'
                }
            }
        }
        stage('Archive Report') {
            steps {
                dir('project2') {
                    archiveArtifacts artifacts: 'report.txt', fingerprint: true
                }
            }
        }
    }
}
